### ISSUE TITLE
Embedded Images

### ISSUE THREAD

**Issue by BlaviButcher** [helicalco/docs#3]
I'm able to embed images in markdown on vscode just fine using ![](./images/settings-github.png) - renders in preview. However, on the site it will not render. I think screenshots could be super useful in specific use cases. For instance when describing how to add SSH key on github:
Go into settings in github.  
Click on SSH and GPG keys on the left side bar.  
Select new SSH key (green bubble to right).  
Paste the SSH key with whatever title you want and hit Add SSH key.

**Comment by jhwz** [comment]
Use `..`
